package br.com.catalisa.GestaoDeEstoque.enums;

public enum TipoLogEvento {

    LISTOU_PRODUTOS,
    LISTOU_PRODUTO,
    PRODUTO_CADASTRADO,
    PRODUTO_ALTERADO,
    PRODUTO_DELETADO,
    LISTOU_FORNECEDORES,
    LISTOU_FORNECEDOR,
    FORNECEDOR_CADASTRADO,
    FORNECEDOR_ALTERADO,
    FORNECEDOR_DELETADO,
    LISTOU_TODO_ESTOQUE,
    ESTOQUE_CADASTRADO,
    ESTOQUE_ALTERADO

}
